/* Copyright (c) 2014, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/
/*Author:jiao.shp*/

#ifndef _PANEL_BP080WX1_S6D7AA0X01_1280_800_VIDEO_H_
#define _PANEL_BP080WX1_S6D7AA0X01_1280_800_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

#define BP080WX1_S6D7AA0X01_VIDEO_SIGNATURE 0x6247
#define	BP080WX1_S6D7AA0X01_VIDEO_ID 1
#define BP080WX1_S6D7AA0X01_VIDEO_LCD_ADC_STATUS 0
#define	BP080WX1_S6D7AA0X01_VIDEO_IC_TYPE 11
#define	BP080WX1_S6D7AA0X01_VIDEO_LCD_ADC_MAX  1000000
#define	BP080WX1_S6D7AA0X01_VIDEO_LCD_ADC_MIN  0

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config bp080wx1_s6d7aa0x01_1280_800_video_panel_data = {
	"qcom,mdss_dsi_bp080wx1_s6d7aa0x01_1280_800_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution bp080wx1_s6d7aa0x01_1280_800_video_panel_res = {
	800, 1280, 16, 48, 16, 0, 8, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info bp080wx1_s6d7aa0x01_1280_800_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd000[]={0x03,0x00,0x39,0xC0,0xf0,0x5a,0x5a,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd001[]={0x03,0x00,0x39,0xC0,0xf1,0x5a,0x5a,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd002[]={0x03,0x00,0x39,0xC0,0xfc,0xa5,0xa5,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd003[]={0x03,0x00,0x39,0xC0,0xd0,0x00,0x10,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd004[]={0x02,0x00,0x39,0xC0,0xb1,0x10,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd005[]={0x05,0x00,0x39,0xC0,0xb2,0x14,0x22,0x2f,0x04,0xFF,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd006[]={0x06,0x00,0x39,0xC0,0xf2,0x02,0x08,0x08,0x40,0x10,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd007[]={0x02,0x00,0x39,0xC0,0xb0,0x03,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd008[]={0x03,0x00,0x39,0xC0,0xfd,0x23,0x09,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd009[]={0x0b,0x00,0x39,0xC0,0xf3,0x01,0xd7,0xe2,0x62,0xf4,0xf7,0x77,0x3c,0x26,0x00,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd010[]={0x2e,0x00,0x39,0xC0,0xf4,0x00,0x02,0x03,0x26,0x03,0x02,0x09,0x00,0x07,0x16,0x16,0x03,0x00,0x08,0x08,0x03,0x0e,0x0f,0x12,0x1c,0x1d,0x1e,0x0c,0x09,0x01,0x04,0x02,0x61,0x74,0x75,0x72,0x83,0x80,0x80,0xb0,0x00,0x01,0x01,0x28,0x04,0x03,0x28,0x01,0xd1,0x32,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd011[]={0x1b,0x00,0x39,0xC0,0xf5,0x84,0x2f,0x2f,0x5f,0xab,0x98,0x52,0x0f,0x33,0x43,0x04,0x59,0x54,0x52,0x05,0x40,0x60,0x4e,0x60,0x40,0x27,0x26,0x52,0x25,0x6d,0x18,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd012[]={0x09,0x00,0x39,0xC0,0xee,0x25,0x00,0x25,0x00,0x25,0x00,0x25,0x00,0xFF,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd013[]={0x09,0x00,0x39,0xC0,0xef,0x34,0x12,0x98,0xba,0x20,0x00,0x24,0x80,0xFF,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd014[]={0x21,0x00,0x39,0xC0,0xf7,0x0e,0x0e,0x0a,0x0a,0x0f,0x0f,0x0b,0x0b,0x05,0x07,0x01,0x01,0x01,0x01,0x01,0x01,0x0c,0x0c,0x08,0x08,0x0d,0x0d,0x09,0x09,0x04,0x06,0x01,0x01,0x01,0x01,0x01,0x01,0xFF,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd015[]={0x04,0x00,0x39,0xC0,0xbc,0x01,0x4e,0x0a};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd016[]={0x06,0x00,0x39,0xC0,0xe1,0x03,0x10,0x1c,0xa0,0x10,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd017[]={0x07,0x00,0x39,0xC0,0xf6,0x60,0x21,0xa6,0x00,0x00,0x00,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd018[]={0x07,0x00,0x39,0xC0,0xfe,0x00,0x0d,0x03,0x21,0x00,0x48,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd019[]={0x02,0x00,0x39,0xC0,0xb0,0x22,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd020[]={0x12,0x00,0x39,0xC0,0xfa,0x02,0x34,0x09,0x13,0x0b,0x0f,0x16,0x16,0x17,0x1e,0x1d,0x1c,0x1e,0x1d,0x1d,0x1f,0x24,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd021[]={0x02,0x00,0x39,0xC0,0xb0,0x22,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd022[]={0x12,0x00,0x39,0xC0,0xfb,0x00,0x34,0x07,0x11,0x09,0x0d,0x14,0x14,0x15,0x1c,0x1f,0x1c,0x1d,0x1d,0x1d,0x20,0x26,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd023[]={0x02,0x00,0x39,0xC0,0xb0,0x11,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd024[]={0x12,0x00,0x39,0xC0,0xfa,0x20,0x34,0x24,0x27,0x19,0x1b,0x1f,0x1e,0x1b,0x1f,0x21,0x1f,0x1e,0x20,0x1e,0x1e,0x21,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd025[]={0x02,0x00,0x39,0xC0,0xb0,0x11,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd026[]={0x12,0x00,0x39,0xC0,0xfb,0x1e,0x34,0x22,0x25,0x17,0x19,0x1d,0x1a,0x19,0x20,0x1f,0x1e,0x20,0x1e,0x1e,0x1f,0x22,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd027[]={0x12,0x00,0x39,0xC0,0xfa,0x1c,0x34,0x1c,0x1f,0x13,0x17,0x1a,0x18,0x18,0x1e,0x20,0x21,0x21,0x21,0x23,0x22,0x2a,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd028[]={0x12,0x00,0x39,0xC0,0xfb,0x1a,0x34,0x1a,0x1d,0x11,0x15,0x18,0x16,0x16,0x1c,0x20,0x20,0x20,0x1f,0x23,0x23,0x2b,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd029[]={0x02,0x00,0x39,0xC0,0x11,0x00,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd030[]={0x04,0x00,0x39,0xC0,0xc3,0x40,0x00,0x28};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd031[]={0x02,0x00,0x39,0xC0,0x35,0x00,0xFF,0xFF};
static char bp080wx1_s6d7aa0x01_1280_800_video_on_cmd032[]={0x02,0x00,0x39,0xC0,0x29,0x00,0xFF,0xFF};


#define PANEL_DELAY 0

static struct mipi_dsi_cmd bp080wx1_s6d7aa0x01_1280_800_video_on_command[] = {
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd000), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd000, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd001), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd001, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd002), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd002, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd003), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd003, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd004), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd004, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd005), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd005, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd006), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd006, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd007), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd007, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd008), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd008, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd009), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd009, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd010), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd010, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd011), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd011, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd012), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd012, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd013), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd013, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd014), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd014, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd015), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd015, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd016), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd016, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd017), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd017, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd018), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd018, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd019), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd019, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd020), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd020, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd021), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd021, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd022), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd022, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd023), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd023, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd024), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd024, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd025), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd025, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd026), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd026, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd027), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd027, PANEL_DELAY},	
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd028), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd028, PANEL_DELAY},	
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd029), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd029, 10},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd030), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd030, 120},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd031), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd031, PANEL_DELAY},
	{sizeof(bp080wx1_s6d7aa0x01_1280_800_video_on_cmd032), bp080wx1_s6d7aa0x01_1280_800_video_on_cmd032, 40},	
};

#define BP080WX1_S6D7AA0X01_1280_800_VIDEO_ON_COMMAND ARRAY_SIZE(bp080wx1_s6d7aa0x01_1280_800_video_on_command)


static char bp080wx1_s6d7aa0x01_1280_800_video_off_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char bp080wx1_s6d7aa0x01_1280_800_video_off_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd bp080wx1_s6d7aa0x01_1280_800_video_off_command[] = {
	{0x4, bp080wx1_s6d7aa0x01_1280_800_video_off_cmd0, 0x28},
	{0x4, bp080wx1_s6d7aa0x01_1280_800_video_off_cmd1, 0x78}
};

#define BP080WX1_S6D7AA0X01_1280_800_VIDEO_OFF_COMMAND ARRAY_SIZE(bp080wx1_s6d7aa0x01_1280_800_video_off_command)


static struct command_state bp080wx1_s6d7aa0x01_1280_800_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info bp080wx1_s6d7aa0x01_1280_800_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info bp080wx1_s6d7aa0x01_1280_800_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration bp080wx1_s6d7aa0x01_1280_800_video_lane_config = {
	4, 0, 1, 1, 1, 1
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t bp080wx1_s6d7aa0x01_1280_800_video_timings[] = {
	0x7B, 0x1A, 0x10, 0x00, 0x3C, 0x42, 0x14, 0x1C, 0x15, 0x03, 0x04, 0x00
};

static struct panel_timing bp080wx1_s6d7aa0x01_1280_800_video_timing_info = {
	0, 4, 0x20, 0x3e
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence bp080wx1_s6d7aa0x01_1280_800_video_reset_seq = {
	{1, 0, 1, }, {20, 20, 120, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight bp080wx1_s6d7aa0x01_1280_800_video_backlight = {
  1, 1, 255, 100, 2, "PMIC_8941"
};
#endif /*_PANEL_BP080WX1_S6D7AA0X01_1280_800_VIDEO_H_*/

