/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
/* zhouwentao modify porch for QL1000 onus hengkaihui hx8389b 2014.8.6*/
/*zhouwentao update para for onus hengkaihui 2014.8.6*/
/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_LEAD_OTM1284_HD_CPT_550_VIDEO_H_

#define _PANEL_LEAD_OTM1284_HD_CPT_550_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"
#define OTM1284_LEAD_HD_CPT_550_VIDEO_SIGNATURE 0x1284
#define OTM1284_LEAD_HD_CPT_550_VIDEO_ID 1
#define OTM1284_LEAD_HD_CPT_550_VIDEO_ADC_STATUS 0
#define	OTM1284_LEAD_HD_CPT_550_VIDEO_IC_TYPE 1
#define	OTM1284_LEAD_HD_CPT_550_VIDEO_ADC_MAX  1000000
#define	OTM1284_LEAD_HD_CPT_550_VIDEO_ADC_MIN   0

#define CMD_DELAY 0x10
/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config otm1284_lead_hd_cpt_hd_550_video_panel_data = {
  "qcom,mdss_dsi_lead_otm1284_720p_cpt_video", "dsi:0:", "qcom,mdss-dsi-panel",
  10, 0, "DISPLAY_1", 0, 0, 55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution otm1284_lead_hd_cpt_hd_550_video_panel_res = {
	720, 1280, 120, 250, 20, 0, 21, 17, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0
  
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info otm1284_lead_hd_cpt_hd_550_video_color = {
  24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/
static char mipi_otm1284_lead_hd_cpt_cmd0[]={0x02,0x00,0x39,0xc0,0x00,0x00,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd1[]={0x04,0x00,0x39,0xc0,0xff,0x12,0x84,0x01};
static char mipi_otm1284_lead_hd_cpt_cmd2[]={0x02,0x00,0x39,0xc0,0x00,0x80,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd3[]={0x03,0x00,0x39,0xc0,0xff,0x12,0x84,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd4[]={0x02,0x00,0x39,0xc0,0x00,0x92,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd5[]={0x03,0x00,0x39,0xc0,0xff,0x30,0x02,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd6[]={0x02,0x00,0x39,0xc0,0x00,0x80,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd7[]={0x0a,0x00,0x39,0xc0,0xc0,0x00,0x64,0x00,0x10,0x10,0x00,0x64,0x10,0x10,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd8[]={0x02,0x00,0x39,0xc0,0x00,0x90,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd9[]={0x07,0x00,0x39,0xc0,0xc0,0x00,0x5c,0x00,0x01,0x00,0x04,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd10[]={0x02,0x00,0x39,0xc0,0x00,0xb3,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd11[]={0x03,0x00,0x39,0xc0,0xc0,0x00,0x55,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd12[]={0x02,0x00,0x39,0xc0,0x00,0x81,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd13[]={0x02,0x00,0x39,0xc0,0xc1,0x55,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd14[]={0x02,0x00,0x39,0xc0,0x00,0xa0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd15[]={0x0f,0x00,0x39,0xc0,0xc4,0x05,0x10,0x06,0x02,0x05,0x15,0x10,0x05,0x10,0x07,0x02,0x05,0x15,0x10,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd16[]={0x02,0x00,0x39,0xc0,0x00,0xb0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd17[]={0x03,0x00,0x39,0xc0,0xc4,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd18[]={0x02,0x00,0x39,0xc0,0x00,0x91,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd19[]={0x03,0x00,0x39,0xc0,0xc5,0x46,0x42,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd20[]={0x02,0x00,0x39,0xc0,0x00,0x00,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd21[]={0x03,0x00,0x39,0xc0,0xd8,0xbc,0xbc,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd22[]={0x02,0x00,0x39,0xc0,0x00,0x00,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd23[]={0x02,0x00,0x39,0xc0,0xd9,0x62,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd24[]={0x02,0x00,0x39,0xc0,0x00,0xb3,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd25[]={0x02,0x00,0x39,0xc0,0xc5,0x84,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd26[]={0x02,0x00,0x39,0xc0,0x00,0xbb,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd27[]={0x02,0x00,0x39,0xc0,0xc5,0x8a,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd28[]={0x02,0x00,0x39,0xc0,0x00,0x82,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd29[]={0x02,0x00,0x39,0xc0,0xc4,0x0a,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd30[]={0x02,0x00,0x39,0xc0,0x00,0xc6,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd31[]={0x02,0x00,0x39,0xc0,0xb0,0x03,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd32[]={0x02,0x00,0x39,0xc0,0x00,0xc2,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd33[]={0x02,0x00,0x39,0xc0,0xf5,0x40,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd34[]={0x02,0x00,0x39,0xc0,0x00,0xc3,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd35[]={0x02,0x00,0x39,0xc0,0xf5,0x85,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd36[]={0x02,0x00,0x39,0xc0,0x00,0x87,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd37[]={0x02,0x00,0x39,0xc0,0xc4,0x18,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd38[]={0x02,0x00,0x39,0xc0,0x00,0x00,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd39[]={0x02,0x00,0x39,0xc0,0xd0,0x40,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd40[]={0x02,0x00,0x39,0xc0,0x00,0x00,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd41[]={0x03,0x00,0x39,0xc0,0xd1,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd42[]={0x02,0x00,0x39,0xc0,0x00,0x80,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd43[]={0x0c,0x00,0x39,0xc0,0xcb,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
static char mipi_otm1284_lead_hd_cpt_cmd44[]={0x02,0x00,0x39,0xc0,0x00,0x90,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd45[]={0x10,0x00,0x39,0xc0,0xcb,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
static char mipi_otm1284_lead_hd_cpt_cmd46[]={0x02,0x00,0x39,0xc0,0x00,0xa0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd47[]={0x10,0x00,0x39,0xc0,0xcb,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
static char mipi_otm1284_lead_hd_cpt_cmd48[]={0x02,0x00,0x39,0xc0,0x00,0xb0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd49[]={0x10,0x00,0x39,0xc0,0xcb,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
static char mipi_otm1284_lead_hd_cpt_cmd50[]={0x02,0x00,0x39,0xc0,0x00,0xc0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd51[]={0x10,0x00,0x39,0xc0,0xcb,0x05,0x05,0x05,0x05,0x05,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
static char mipi_otm1284_lead_hd_cpt_cmd52[]={0x02,0x00,0x39,0xc0,0x00,0xd0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd53[]={0x10,0x00,0x39,0xc0,0xcb,0xff,0xff,0xff,0x00,0x05,0x05,0x05,0x05,0x05,0x05,0x05,0x05,0x00,0x00,0x00};
static char mipi_otm1284_lead_hd_cpt_cmd54[]={0x02,0x00,0x39,0xc0,0x00,0xe0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd55[]={0x0f,0x00,0x39,0xc0,0xcb,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0xff,0x00,0x05,0x05,0x05,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd56[]={0x02,0x00,0x39,0xc0,0x00,0xf0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd57[]={0x0c,0x00,0x39,0xc0,0xcb,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff};
static char mipi_otm1284_lead_hd_cpt_cmd58[]={0x02,0x00,0x39,0xc0,0x00,0x80,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd59[]={0x10,0x00,0x39,0xc0,0xcc,0x02,0x0a,0x0c,0x0e,0x10,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
static char mipi_otm1284_lead_hd_cpt_cmd60[]={0x02,0x00,0x39,0xc0,0x00,0x90,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd61[]={0x10,0x00,0x39,0xc0,0xcc,0x00,0x00,0x00,0x00,0x2e,0x2d,0x06,0x01,0x09,0x0b,0x0d,0x0f,0x00,0x00,0x00};
static char mipi_otm1284_lead_hd_cpt_cmd62[]={0x02,0x00,0x39,0xc0,0x00,0xa0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd63[]={0x0f,0x00,0x39,0xc0,0xcc,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x2e,0x2d,0x05,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd64[]={0x02,0x00,0x39,0xc0,0x00,0xb0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd65[]={0x10,0x00,0x39,0xc0,0xcc,0x05,0x0f,0x0d,0x0b,0x09,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
static char mipi_otm1284_lead_hd_cpt_cmd66[]={0x02,0x00,0x39,0xc0,0x00,0xc0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd67[]={0x10,0x00,0x39,0xc0,0xcc,0x00,0x00,0x00,0x00,0x2d,0x2e,0x01,0x06,0x10,0x0e,0x0c,0x0a,0x00,0x00,0x00};
static char mipi_otm1284_lead_hd_cpt_cmd68[]={0x02,0x00,0x39,0xc0,0x00,0xd0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd69[]={0x0f,0x00,0x39,0xc0,0xcc,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x2d,0x2e,0x02,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd70[]={0x02,0x00,0x39,0xc0,0x00,0x80,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd71[]={0x0d,0x00,0x39,0xc0,0xce,0x87,0x03,0x10,0x86,0x03,0x10,0x00,0x00,0x00,0x00,0x00,0x00,0xFF,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd72[]={0x02,0x00,0x39,0xc0,0x00,0x90,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd73[]={0x0f,0x00,0x39,0xc0,0xce,0x35,0x01,0x10,0x35,0x02,0x10,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd74[]={0x02,0x00,0x39,0xc0,0x00,0xa0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd75[]={0x0f,0x00,0x39,0xc0,0xce,0x38,0x03,0x04,0xf8,0x00,0x10,0x00,0x38,0x02,0x04,0xf9,0x00,0x10,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd76[]={0x02,0x00,0x39,0xc0,0x00,0xb0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd77[]={0x0f,0x00,0x39,0xc0,0xce,0x38,0x01,0x04,0xfa,0x00,0x10,0x00,0x38,0x00,0x04,0xfb,0x00,0x10,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd78[]={0x02,0x00,0x39,0xc0,0x00,0xc0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd79[]={0x0f,0x00,0x39,0xc0,0xce,0x30,0x00,0x04,0xfc,0x00,0x10,0x00,0x30,0x01,0x04,0xfd,0x00,0x10,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd80[]={0x02,0x00,0x39,0xc0,0x00,0xd0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd81[]={0x0f,0x00,0x39,0xc0,0xce,0x30,0x02,0x04,0xfe,0x00,0x10,0x00,0x30,0x03,0x04,0xff,0x00,0x10,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd82[]={0x02,0x00,0x39,0xc0,0x00,0x80,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd83[]={0x0f,0x00,0x39,0xc0,0xcf,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd84[]={0x02,0x00,0x39,0xc0,0x00,0x90,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd85[]={0x0f,0x00,0x39,0xc0,0xcf,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd86[]={0x02,0x00,0x39,0xc0,0x00,0xa0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd87[]={0x0f,0x00,0x39,0xc0,0xcf,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd88[]={0x02,0x00,0x39,0xc0,0x00,0xb0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd89[]={0x0f,0x00,0x39,0xc0,0xcf,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd90[]={0x02,0x00,0x39,0xc0,0x00,0xc0,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd91[]={0x0c,0x00,0x39,0xc0,0xcf,0x01,0x01,0x20,0x20,0x00,0x00,0x01,0x81,0x00,0x03,0x08};
static char mipi_otm1284_lead_hd_cpt_cmd92[]={0x02,0x00,0x39,0xc0,0x00,0xb5,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd93[]={0x07,0x00,0x39,0xc0,0xc5,0x3f,0xff,0xff,0x3f,0xff,0xff,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd94[]={0x02,0x00,0x39,0xc0,0x00,0x90,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd95[]={0x05,0x00,0x39,0xc0,0xf5,0x02,0x11,0x02,0x15,0xFF,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd96[]={0x02,0x00,0x39,0xc0,0x00,0x90,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd97[]={0x02,0x00,0x39,0xc0,0xc5,0x50,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd98[]={0x02,0x00,0x39,0xc0,0x00,0x94,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd99[]={0x02,0x00,0x39,0xc0,0xc5,0x66,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd100[]={0x02,0x00,0x39,0xc0,0x00,0xb2,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd101[]={0x03,0x00,0x39,0xc0,0xf5,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd102[]={0x02,0x00,0x39,0xc0,0x00,0xb4,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd103[]={0x03,0x00,0x39,0xc0,0xf5,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd104[]={0x02,0x00,0x39,0xc0,0x00,0xb6,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd105[]={0x03,0x00,0x39,0xc0,0xf5,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd106[]={0x02,0x00,0x39,0xc0,0x00,0xb8,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd107[]={0x03,0x00,0x39,0xc0,0xf5,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd108[]={0x02,0x00,0x39,0xc0,0x00,0x94,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd109[]={0x03,0x00,0x39,0xc0,0xf5,0x00,0x00,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd110[]={0x02,0x00,0x39,0xc0,0x00,0xd2,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd111[]={0x03,0x00,0x39,0xc0,0xf5,0x06,0x15,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd112[]={0x02,0x00,0x39,0xc0,0x00,0xb4,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd113[]={0x02,0x00,0x39,0xc0,0xc5,0xcc,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd114[]={0x02,0x00,0x39,0xc0,0x00,0x00,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd115[]={0x15,0x00,0x39,0xc0,0xE1,0x00,0x14,0x22,0x2E,0x40,0x4E,0x51,0x81,0x75,0x92,0x6F,0x58,0x6A,0x48,0x47,0x3C,0x2E,0x1F,0x0E,0x00,0xFF,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd116[]={0x02,0x00,0x39,0xc0,0x00,0x00,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd117[]={0x15,0x00,0x39,0xc0,0xE2,0x00,0x14,0x22,0x2E,0x40,0x4E,0x51,0x81,0x75,0x92,0x70,0x59,0x6B,0x47,0x47,0x3C,0x2E,0x1F,0x0E,0x00,0xFF,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd118[]={0x02,0x00,0x39,0xc0,0x00,0x00,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd119[]={0x04,0x00,0x39,0xc0,0xff,0xff,0xff,0xff};
static char mipi_otm1284_lead_hd_cpt_cmd120[]={0x02,0x00,0x39,0xc0,0x11,0x00,0xFF,0xFF};
static char mipi_otm1284_lead_hd_cpt_cmd121[]={0x02,0x00,0x39,0xc0,0x29,0x00,0xFF,0xFF};

static struct mipi_dsi_cmd otm1284_lead_hd_cpt_hd_550_video_on_command[] = {
{sizeof(mipi_otm1284_lead_hd_cpt_cmd0), (char *)mipi_otm1284_lead_hd_cpt_cmd0,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd1), (char *)mipi_otm1284_lead_hd_cpt_cmd1,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd2), (char *)mipi_otm1284_lead_hd_cpt_cmd2,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd3), (char *)mipi_otm1284_lead_hd_cpt_cmd3,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd4), (char *)mipi_otm1284_lead_hd_cpt_cmd4,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd5), (char *)mipi_otm1284_lead_hd_cpt_cmd5,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd6), (char *)mipi_otm1284_lead_hd_cpt_cmd6,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd7), (char *)mipi_otm1284_lead_hd_cpt_cmd7,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd8), (char *)mipi_otm1284_lead_hd_cpt_cmd8,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd9), (char *)mipi_otm1284_lead_hd_cpt_cmd9,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd10), (char *)mipi_otm1284_lead_hd_cpt_cmd10,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd11), (char *)mipi_otm1284_lead_hd_cpt_cmd11,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd12), (char *)mipi_otm1284_lead_hd_cpt_cmd12,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd13), (char *)mipi_otm1284_lead_hd_cpt_cmd13,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd14), (char *)mipi_otm1284_lead_hd_cpt_cmd14,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd15), (char *)mipi_otm1284_lead_hd_cpt_cmd15,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd16), (char *)mipi_otm1284_lead_hd_cpt_cmd16,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd17), (char *)mipi_otm1284_lead_hd_cpt_cmd17,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd18), (char *)mipi_otm1284_lead_hd_cpt_cmd18,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd19), (char *)mipi_otm1284_lead_hd_cpt_cmd19,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd20), (char *)mipi_otm1284_lead_hd_cpt_cmd20,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd21), (char *)mipi_otm1284_lead_hd_cpt_cmd21,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd22), (char *)mipi_otm1284_lead_hd_cpt_cmd22,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd23), (char *)mipi_otm1284_lead_hd_cpt_cmd23,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd24), (char *)mipi_otm1284_lead_hd_cpt_cmd24,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd25), (char *)mipi_otm1284_lead_hd_cpt_cmd25,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd26), (char *)mipi_otm1284_lead_hd_cpt_cmd26,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd27), (char *)mipi_otm1284_lead_hd_cpt_cmd27,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd28), (char *)mipi_otm1284_lead_hd_cpt_cmd28,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd29), (char *)mipi_otm1284_lead_hd_cpt_cmd29,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd30), (char *)mipi_otm1284_lead_hd_cpt_cmd30,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd31), (char *)mipi_otm1284_lead_hd_cpt_cmd31,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd32), (char *)mipi_otm1284_lead_hd_cpt_cmd32,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd33), (char *)mipi_otm1284_lead_hd_cpt_cmd33,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd34), (char *)mipi_otm1284_lead_hd_cpt_cmd34,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd35), (char *)mipi_otm1284_lead_hd_cpt_cmd35,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd36), (char *)mipi_otm1284_lead_hd_cpt_cmd36,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd37), (char *)mipi_otm1284_lead_hd_cpt_cmd37,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd38), (char *)mipi_otm1284_lead_hd_cpt_cmd38,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd39), (char *)mipi_otm1284_lead_hd_cpt_cmd39,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd40), (char *)mipi_otm1284_lead_hd_cpt_cmd40,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd41), (char *)mipi_otm1284_lead_hd_cpt_cmd41,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd42), (char *)mipi_otm1284_lead_hd_cpt_cmd42,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd43), (char *)mipi_otm1284_lead_hd_cpt_cmd43,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd44), (char *)mipi_otm1284_lead_hd_cpt_cmd44,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd45), (char *)mipi_otm1284_lead_hd_cpt_cmd45,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd46), (char *)mipi_otm1284_lead_hd_cpt_cmd46,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd47), (char *)mipi_otm1284_lead_hd_cpt_cmd47,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd48), (char *)mipi_otm1284_lead_hd_cpt_cmd48,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd49), (char *)mipi_otm1284_lead_hd_cpt_cmd49,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd50), (char *)mipi_otm1284_lead_hd_cpt_cmd50,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd51), (char *)mipi_otm1284_lead_hd_cpt_cmd51,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd52), (char *)mipi_otm1284_lead_hd_cpt_cmd52,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd53), (char *)mipi_otm1284_lead_hd_cpt_cmd53,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd54), (char *)mipi_otm1284_lead_hd_cpt_cmd54,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd55), (char *)mipi_otm1284_lead_hd_cpt_cmd55,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd56), (char *)mipi_otm1284_lead_hd_cpt_cmd56,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd57), (char *)mipi_otm1284_lead_hd_cpt_cmd57,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd58), (char *)mipi_otm1284_lead_hd_cpt_cmd58,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd59), (char *)mipi_otm1284_lead_hd_cpt_cmd59,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd60), (char *)mipi_otm1284_lead_hd_cpt_cmd60,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd61), (char *)mipi_otm1284_lead_hd_cpt_cmd61,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd62), (char *)mipi_otm1284_lead_hd_cpt_cmd62,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd63), (char *)mipi_otm1284_lead_hd_cpt_cmd63,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd64), (char *)mipi_otm1284_lead_hd_cpt_cmd64,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd65), (char *)mipi_otm1284_lead_hd_cpt_cmd65,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd66), (char *)mipi_otm1284_lead_hd_cpt_cmd66,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd67), (char *)mipi_otm1284_lead_hd_cpt_cmd67,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd68), (char *)mipi_otm1284_lead_hd_cpt_cmd68,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd69), (char *)mipi_otm1284_lead_hd_cpt_cmd69,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd70), (char *)mipi_otm1284_lead_hd_cpt_cmd70,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd71), (char *)mipi_otm1284_lead_hd_cpt_cmd71,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd72), (char *)mipi_otm1284_lead_hd_cpt_cmd72,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd73), (char *)mipi_otm1284_lead_hd_cpt_cmd73,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd74), (char *)mipi_otm1284_lead_hd_cpt_cmd74,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd75), (char *)mipi_otm1284_lead_hd_cpt_cmd75,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd76), (char *)mipi_otm1284_lead_hd_cpt_cmd76,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd77), (char *)mipi_otm1284_lead_hd_cpt_cmd77,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd78), (char *)mipi_otm1284_lead_hd_cpt_cmd78,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd79), (char *)mipi_otm1284_lead_hd_cpt_cmd79,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd80), (char *)mipi_otm1284_lead_hd_cpt_cmd80,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd81), (char *)mipi_otm1284_lead_hd_cpt_cmd81,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd82), (char *)mipi_otm1284_lead_hd_cpt_cmd82,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd83), (char *)mipi_otm1284_lead_hd_cpt_cmd83,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd84), (char *)mipi_otm1284_lead_hd_cpt_cmd84,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd85), (char *)mipi_otm1284_lead_hd_cpt_cmd85,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd86), (char *)mipi_otm1284_lead_hd_cpt_cmd86,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd87), (char *)mipi_otm1284_lead_hd_cpt_cmd87,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd88), (char *)mipi_otm1284_lead_hd_cpt_cmd88,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd89), (char *)mipi_otm1284_lead_hd_cpt_cmd89,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd90), (char *)mipi_otm1284_lead_hd_cpt_cmd90,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd91), (char *)mipi_otm1284_lead_hd_cpt_cmd91,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd92), (char *)mipi_otm1284_lead_hd_cpt_cmd92,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd93), (char *)mipi_otm1284_lead_hd_cpt_cmd93,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd94), (char *)mipi_otm1284_lead_hd_cpt_cmd94,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd95), (char *)mipi_otm1284_lead_hd_cpt_cmd95,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd96), (char *)mipi_otm1284_lead_hd_cpt_cmd96,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd97), (char *)mipi_otm1284_lead_hd_cpt_cmd97,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd98), (char *)mipi_otm1284_lead_hd_cpt_cmd98,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd99), (char *)mipi_otm1284_lead_hd_cpt_cmd99,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd100), (char *)mipi_otm1284_lead_hd_cpt_cmd100,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd101), (char *)mipi_otm1284_lead_hd_cpt_cmd101,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd102), (char *)mipi_otm1284_lead_hd_cpt_cmd102,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd103), (char *)mipi_otm1284_lead_hd_cpt_cmd103,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd104), (char *)mipi_otm1284_lead_hd_cpt_cmd104,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd105), (char *)mipi_otm1284_lead_hd_cpt_cmd105,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd106), (char *)mipi_otm1284_lead_hd_cpt_cmd106,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd107), (char *)mipi_otm1284_lead_hd_cpt_cmd107,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd108), (char *)mipi_otm1284_lead_hd_cpt_cmd108,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd109), (char *)mipi_otm1284_lead_hd_cpt_cmd109,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd110), (char *)mipi_otm1284_lead_hd_cpt_cmd110,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd111), (char *)mipi_otm1284_lead_hd_cpt_cmd111,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd112), (char *)mipi_otm1284_lead_hd_cpt_cmd112,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd113), (char *)mipi_otm1284_lead_hd_cpt_cmd113,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd114), (char *)mipi_otm1284_lead_hd_cpt_cmd114,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd115), (char *)mipi_otm1284_lead_hd_cpt_cmd115,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd116), (char *)mipi_otm1284_lead_hd_cpt_cmd116,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd117), (char *)mipi_otm1284_lead_hd_cpt_cmd117,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd118), (char *)mipi_otm1284_lead_hd_cpt_cmd118,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd119), (char *)mipi_otm1284_lead_hd_cpt_cmd119,CMD_DELAY},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd120), (char *)mipi_otm1284_lead_hd_cpt_cmd120,150},
{sizeof(mipi_otm1284_lead_hd_cpt_cmd121), (char *)mipi_otm1284_lead_hd_cpt_cmd121,50},
};

#define OTM1284_LEAD_HD_CPT_550_VIDEO_ON_COMMAND 122


static char otm1284_lead_hd_cpt_hd_550_videooff_cmd0[] = {
0x28, 0x00, 0x05, 0x80 };


static char otm1284_lead_hd_cpt_hd_550_videooff_cmd1[] = {
0x10, 0x00, 0x05, 0x80 };




static struct mipi_dsi_cmd otm1284_lead_hd_cpt_hd_550_video_off_command[] = {
{ 0x4 , otm1284_lead_hd_cpt_hd_550_videooff_cmd0},
{ 0x4 , otm1284_lead_hd_cpt_hd_550_videooff_cmd1}
};
#define OTM1284_LEAD_HD_CPT_550_VIDEO_OFF_COMMAND 2


static struct command_state otm1284_lead_hd_cpt_hd_550_video_state = {
  0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info otm1284_lead_hd_cpt_hd_550_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info otm1284_lead_hd_cpt_hd_550_video_video_panel = {
  1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration otm1284_lead_hd_cpt_hd_550_video_lane_config = {
  4, 0, 1, 1, 1, 1
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
const uint32_t otm1284_lead_hd_cpt_hd_550_video_timings[] = {
  //0xf7, 0x23, 0x1c, 0x00, 0x33, 0x33, 0x1d, 0x25, 0x2d, 0x03, 0x04, 0x00
  0x7D, 0x24,0x19,0x00,0x34,0x2F,0x1E,0x26,0x2A,0x03,0x04,0x00
};



static struct mipi_dsi_cmd otm1284_lead_hd_cpt_hd_550_video_rotation[] = {

};
#define OTM1284_LEAD_HD_CPT_550_VIDEO_ROTATION 0


static struct panel_timing otm1284_lead_hd_cpt_hd_550_video_timing_info = {
  0, 4, 0x20, 0x34
};

static struct panel_reset_sequence otm1284_lead_hd_cpt_hd_550_video_panel_reset_seq = {
{ 1, 0, 1, }, { 50, 50, 150, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight otm1284_lead_hd_cpt_hd_550_video_backlight = {
  1, 1, 255, 100, 2, "PMIC_8941"
};


#endif /*_PANEL_LEAD_OTM1284_HD_CPT_550_VIDEO_H_*/
