/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
/* zhouwentao modify porch for QL1000 onus hengkaihui hx8389b 2014.8.6*/
/*zhouwentao update para for onus hengkaihui 2014.8.6*/
/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_TXD_H8394D_HD_INNOLUX_550_VIDEO_H_

#define _PANEL_TXD_H8394D_HD_INNOLUX_550_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"
#define H8394D_TXD_HD_INNOLUX_550_VIDEO_SIGNATURE 0x8394D
#define H8394D_TXD_HD_INNOLUX_550_VIDEO_ID 0
#define H8394D_TXD_HD_INNOLUX_550_VIDEO_ADC_STATUS 0
#define	H8394D_TXD_HD_INNOLUX_550_VIDEO_IC_TYPE 10
#define	H8394D_TXD_HD_INNOLUX_550_VIDEO_ADC_MAX  0
#define	H8394D_TXD_HD_INNOLUX_550_VIDEO_ADC_MIN   0

#define CMD_DELAY 0x10
/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config h8394d_txd_hd_innolux_hd_550_video_panel_data = {
  "qcom,mdss_dsi_h8394d_txd_innolux5p5_hd_video", "dsi:0:", "qcom,mdss-dsi-panel",
  10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution h8394d_txd_hd_innolux_hd_550_video_panel_res = {
	720, 1280, 100, 100, 8, 0, 20, 14, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
  
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info h8394d_txd_hd_innolux_hd_550_video_color = {
  24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/
static char mipi_h8394d_txd_hd_innolux_cmd000[]={0x04,0x00,0x39,0xC0,0xb9,0xff,0x83,0x94};
static char mipi_h8394d_txd_hd_innolux_cmd001[]={0x03,0x00,0x39,0xC0,0xba,0x33,0x83,0xFF};
static char mipi_h8394d_txd_hd_innolux_cmd002[]={0x10,0x00,0x39,0xC0,0xb1,0x6c,0x0f,0x0f,0x34,0x04,0x11,0xf1,0x81,0x2e,0x9f,0x23,0x80,0xc0,0xd2,0x58};
static char mipi_h8394d_txd_hd_innolux_cmd003[]={0x0c,0x00,0x39,0xC0,0xb2,0x00,0x64,0x0e,0x0d,0x32,0x1c,0x08,0x08,0x1c,0x4d,0x00};
static char mipi_h8394d_txd_hd_innolux_cmd004[]={0x0d,0x00,0x39,0xC0,0xb4,0x00,0xff,0x51,0x5a,0x59,0x5a,0x03,0x5a,0x01,0x6a,0x01,0x6a,0xFF,0xFF,0xFF};
static char mipi_h8394d_txd_hd_innolux_cmd005[]={0x26,0x00,0x39,0xC0,0xd3,0x00,0x07,0x00,0x40,0x07,0x10,0x00,0x08,0x10,0x08,0x00,0x08,0x54,0x15,0x0e,0x05,0x0e,0x02,0x15,0x06,0x05,0x06,0x47,0x44,0x0a,0x0a,0x4b,0x10,0x07,0x07,0x08,0x00,0x00,0x00,0x0a,0x00,0x01,0xFF,0xFF};
static char mipi_h8394d_txd_hd_innolux_cmd006[]={0x2d,0x00,0x39,0xC0,0xd5,0x1a,0x1a,0x1b,0x1b,0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0a,0x0b,0x24,0x25,0x18,0x18,0x26,0x27,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x20,0x21,0x18,0x18,0x18,0x18,0xFF,0xFF,0xFF};
static char mipi_h8394d_txd_hd_innolux_cmd007[]={0x2d,0x00,0x39,0xC0,0xd6,0x1a,0x1a,0x1b,0x1b,0x0b,0x0a,0x09,0x08,0x07,0x06,0x05,0x04,0x03,0x02,0x01,0x00,0x21,0x20,0x58,0x58,0x27,0x26,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x25,0x24,0x18,0x18,0x18,0x18,0xFF,0xFF,0xFF};
static char mipi_h8394d_txd_hd_innolux_cmd008[]={0x2b,0x00,0x39,0xC0,0xe0,0x00,0x05,0x0a,0x1e,0x1a,0x3f,0x16,0x34,0x06,0x0a,0x0c,0x17,0x0e,0x11,0x14,0x12,0x13,0x0a,0x13,0x14,0x16,0x00,0x05,0x0a,0x1e,0x1a,0x3f,0x16,0x34,0x06,0x0a,0x0c,0x17,0x0e,0x11,0x14,0x12,0x13,0x0a,0x13,0x14,0x16,0xFF};
static char mipi_h8394d_txd_hd_innolux_cmd009[]={0x02,0x00,0x39,0xC0,0xcc,0x09,0xFF,0xFF};
static char mipi_h8394d_txd_hd_innolux_cmd010[]={0x05,0x00,0x39,0xC0,0xc7,0x00,0xc0,0x00,0xc0,0xFF,0xFF,0xFF};
static char mipi_h8394d_txd_hd_innolux_cmd011[]={0x03,0x00,0x39,0xC0,0xb6,0x46,0x46,0xFF};
static char mipi_h8394d_txd_hd_innolux_cmd012[]={0x02,0x00,0x39,0xC0,0x11,0x00,0xFF,0xFF};
static char mipi_h8394d_txd_hd_innolux_cmd013[]={0x02,0x00,0x39,0xC0,0x29,0x00,0xFF,0xFF};

static struct mipi_dsi_cmd h8394d_txd_hd_innolux_hd_550_video_on_command[] = {
{sizeof(mipi_h8394d_txd_hd_innolux_cmd000), (char *)mipi_h8394d_txd_hd_innolux_cmd000,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd001), (char *)mipi_h8394d_txd_hd_innolux_cmd001,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd002), (char *)mipi_h8394d_txd_hd_innolux_cmd002,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd003), (char *)mipi_h8394d_txd_hd_innolux_cmd003,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd004), (char *)mipi_h8394d_txd_hd_innolux_cmd004,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd005), (char *)mipi_h8394d_txd_hd_innolux_cmd005,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd006), (char *)mipi_h8394d_txd_hd_innolux_cmd006,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd007), (char *)mipi_h8394d_txd_hd_innolux_cmd007,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd008), (char *)mipi_h8394d_txd_hd_innolux_cmd008,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd009), (char *)mipi_h8394d_txd_hd_innolux_cmd009,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd010), (char *)mipi_h8394d_txd_hd_innolux_cmd010,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd011), (char *)mipi_h8394d_txd_hd_innolux_cmd011,CMD_DELAY},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd012), (char *)mipi_h8394d_txd_hd_innolux_cmd012,150},
{sizeof(mipi_h8394d_txd_hd_innolux_cmd013), (char *)mipi_h8394d_txd_hd_innolux_cmd013,50},
};

#define H8394D_TXD_HD_INNOLUX_550_VIDEO_ON_COMMAND  ARRAY_SIZE(h8394d_txd_hd_innolux_hd_550_video_on_command)

static char h8394d_txd_hd_innolux_hd_550_videooff_cmd0[] = {
0x28, 0x00, 0x05, 0x80 };


static char h8394d_txd_hd_innolux_hd_550_videooff_cmd1[] = {
0x10, 0x00, 0x05, 0x80 };




static struct mipi_dsi_cmd h8394d_txd_hd_innolux_hd_550_video_off_command[] = {
{ 0x4 , h8394d_txd_hd_innolux_hd_550_videooff_cmd0},
{ 0x4 , h8394d_txd_hd_innolux_hd_550_videooff_cmd1}
};
#define H8394D_TXD_HD_INNOLUX_550_VIDEO_OFF_COMMAND 2


static struct command_state h8394d_txd_hd_innolux_hd_550_video_state = {
  0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info h8394d_txd_hd_innolux_hd_550_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info h8394d_txd_hd_innolux_hd_550_video_video_panel = {
  1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration h8394d_txd_hd_innolux_hd_550_video_lane_config = {
  4, 0, 1, 1, 1, 1
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
const uint32_t h8394d_txd_hd_innolux_hd_550_video_timings[] = {
  0xE7,0x36,0x24,0x00,0x66,0x6A,0x2A,0x3A,0x2D,0x03,0x04,0x00
};



static struct mipi_dsi_cmd h8394d_txd_hd_innolux_hd_550_video_rotation[] = {

};
#define H8394D_TXD_HD_INNOLUX_550_VIDEO_ROTATION 0


static struct panel_timing h8394d_txd_hd_innolux_hd_550_video_timing_info = {
  0, 4, 0x03, 0x35
};

static struct panel_reset_sequence h8394d_txd_hd_innolux_hd_550_video_panel_reset_seq = {
{ 1, 0, 1, }, { 50, 50, 150, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight h8394d_txd_hd_innolux_hd_550_video_backlight = {
  1, 1, 255, 100, 2, "PMIC_8941"
};


#endif /*_PANEL_TXD_H8394D_HD_INNOLUX_550_VIDEO_H_*/
