/* Copyright (c) 2014, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/
/*Author:jiao.shp*/

#ifndef _PANEL_SAMSUNG_S6D7AA0X01_1280_800_VIDEO_H_
#define _PANEL_SAMSUNG_S6D7AA0X01_1280_800_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

#define SAMSUNG_S6D7AA0X01_VIDEO_SIGNATURE 0x6247
#define	SAMSUNG_S6D7AA0X01_VIDEO_ID 1
#define SAMSUNG_S6D7AA0X01_VIDEO_LCD_ADC_STATUS 0
#define	SAMSUNG_S6D7AA0X01_VIDEO_IC_TYPE 11
#define	SAMSUNG_S6D7AA0X01_VIDEO_LCD_ADC_MAX  1000000
#define	SAMSUNG_S6D7AA0X01_VIDEO_LCD_ADC_MIN  0

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config samsung_s6d7aa0x01_1280_800_video_panel_data = {
	"qcom,mdss_dsi_samsung_s6d7aa0x01_1280_800_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution samsung_s6d7aa0x01_1280_800_video_panel_res = {
	800, 1280, 16, 48, 16, 0, 8, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info samsung_s6d7aa0x01_1280_800_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char samsung_s6d7aa0x01_1280_800_video_on_cmd0 [] = {
    0x03,0x00,0x39,0xC0,
    0xF0,0x5A,0x5A,0XFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd1[] = {
    0x03,0x00,0x39,0xC0,
    0xF1,0x5A,0x5A,0XFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd2[] = {
    0x03,0x00,0x39,0xC0,
    0xFC,0xA5,0xA5,0XFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd3[] = {
    0x02,0x00,0x39,0xC0,
    0xB1,0x10,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd4[] = {
    0x05,0x00,0x39,0xC0,
    0xB2,0x14,0x22,0x2F,
    0x04,0XFF,0XFF,0XFF,
};

static char samsung_s6d7aa0x01_1280_800_video_on_cmd5[] = {
    0x06,0x00,0x39,0xC0,
    0xF2,0x02,0x04,0x08,
    0x30,0x10,0xFF,0xFF,
};

static char samsung_s6d7aa0x01_1280_800_video_on_cmd6[] = {
    0x02,0x00,0x39,0xC0,
    0xB0,0x03,0XFF,0XFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd7[] = {
    0x03,0x00,0x39,0xC0,
    0xFD,0x23,0x09,0XFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd8[] = {
    0x0B,0x00,0x39,0xC0,
    0xF3,0x01,0xD7,0xE2,
    0x62,0xF4,0xF7,0x77,
    0x3C,0x26,0x00,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd9[] = {
    0x12,0x00,0x39,0xC0,
    0xF4,0x00,0x02,0x03,
    0x26,0x03,0x02,0x09,
    0x00,0x07,0x16,0x16,
    0x03,0x00,0x08,0x08,
    0x03,0x0E,0xFF,0xFF,
};

static char samsung_s6d7aa0x01_1280_800_video_on_cmd10[] = {
    0x12,0x00,0x39,0xC0,
    0xF5,0x84,0x2F,0x2F,
    0x5F,0xAB,0x98,0x52,
    0x0F,0x33,0x43,0x04,
    0x59,0x54,0x52,0x05,
    0x40,0x60,0xFF,0xFF,
};

static char samsung_s6d7aa0x01_1280_800_video_on_cmd11[] = {
    0x09,0x00,0x39,0xC0,
    0xEE,0x25,0x00,0x25,
    0x00,0x25,0x00,0x25,
    0x00,0xFF,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd12[] = {
    0x09,0x00,0x39,0xC0,
    0xEF,0x34,0x12,0x98,
    0xBA,0x20,0x00,0x24,
    0x80,0xFF,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd13[] = {
    0x12,0x00,0x39,0xC0,
    0xF7,0x0E,0x0E,0x0A,
    0x0A,0x0F,0x0F,0x0B,
    0x0B,0x05,0x07,0x01,
    0x01,0x01,0x01,0x01,
    0x01,0x0C,0xFF,0xFF,
};

static char samsung_s6d7aa0x01_1280_800_video_on_cmd14[] = {
    0x04,0x00,0x39,0xC0,
    0xBC,0x01,0x4E,0x0A,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd15[] = {
    0x06,0x00,0x39,0xC0,
    0xE1,0x03,0x10,0x1C,
    0xA0,0x10,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd16[] = {
    0x07,0x00,0x39,0xC0,
    0xF6,0x60,0x21,0xA6,
    0x00,0x00,0x00,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd17[] = {
    0x07,0x00,0x39,0xC0,
    0xFE,0x00,0x0D,0x03,
    0x21,0x00,0x48,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd18[] = {
    0x02,0x00,0x39,0xC0,
    0xB0,0x22,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd19[] = {
    0x12,0x00,0x39,0xC0,
    0xFA,0x02,0x34,0x09,
    0x13,0x0B,0x0F,0x16,
    0x16,0x17,0x1E,0x1D,
    0x1C,0x1E,0x1D,0x1D,
    0x1F,0x24,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd20[] = {
    0x02,0x00,0x39,0xC0,
    0xB0,0x22,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd21[] = {
    0x12,0x00,0x39,0xC0,
    0xFB,0x00,0x34,0x07,
    0x11,0x09,0x0D,0x14,
    0x14,0x15,0x1C,0x1F,
    0x1C,0x1D,0x1D,0x1D,
    0x20,0x26,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd22[] = {
    0x02,0x00,0x39,0xC0,
    0xB0,0x11,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd23[] = {
    0x12,0x00,0x39,0xC0,
    0xFA,0x20,0x34,0x24,
    0x27,0x19,0x1B,0x1F,
    0x1E,0x1B,0x1F,0x21,
    0x1F,0x1E,0x20,0x1E,
    0x1E,0x21,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd24[] = {
    0x02,0x00,0x39,0xC0,
    0xB0,0x11,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd25[] = {
    0x12,0x00,0x39,0xC0,
    0xFB,0x1E,0x34,0x22,
    0x25,0x17,0x19,0x1D,
    0x1A,0x19,0x20,0x1F,
    0x1E,0x20,0x1E,0x1E,
    0x1F,0x22,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd26[] = {
    0x12,0x00,0x39,0xC0,
    0xFA,0x1C,0x34,0x1C,
    0x1F,0x13,0x17,0x1A,
    0x18,0x18,0x1E,0x20,
    0x21,0x21,0x21,0x23,
    0x22,0x2A,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd27[] = {
    0x12,0x00,0x39,0xC0,
    0xFB,0x1A,0x34,0x1A,
    0x1D,0x11,0x15,0x18,
    0x16,0x16,0x1C,0x20,
    0x20,0x20,0x1F,0x23,
    0x23,0x2B,0xFF,0xFF,
};

/*CABC Control START*/
static char samsung_s6d7aa0x01_1280_800_video_on_cmd28[] = {
    0x02,0x00,0x39,0xc0,
    0x00,0x00,0xff,0xff
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd29[] = {
    0x02,0x00,0x39,0xc0,
    0x51,0xff,0xff,0xff
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd30[] = {
    0x02,0x00,0x39,0xc0,
    0x00,0x00,0xff,0xff
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd31[] = {
    0x02,0x00,0x39,0xc0,
    0x53,0x2C,0xff,0xff
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd32[] = {
    0x02,0x00,0x39,0xc0,
    0x00,0x00,0xff,0xff
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd33[] = {
    0x02,0x00,0x39,0xc0,
    0x55,0x01,0xff,0xff
};
/*CABC Control END*/

static char samsung_s6d7aa0x01_1280_800_video_on_cmd34[] = {
    0x02,0x00,0x39,0xc0,
    0x11,0x00,0xff,0xff
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd35[] = {
    0x04,0x00,0x39,0xC0,
    0xC3,0x40,0x00,0x28,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd36[] = {
    0x02,0x00,0x39,0xC0,
    0x35,0x00,0xFF,0xFF,
};
static char samsung_s6d7aa0x01_1280_800_video_on_cmd37[] = {
    0x02,0x00,0x39,0xc0,
    0x29,0x00,0xff,0xff
};
#define PANEL_DELAY 0

static struct mipi_dsi_cmd samsung_s6d7aa0x01_1280_800_video_on_command[] = {
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd0), samsung_s6d7aa0x01_1280_800_video_on_cmd0, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd1), samsung_s6d7aa0x01_1280_800_video_on_cmd1, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd2), samsung_s6d7aa0x01_1280_800_video_on_cmd2, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd3), samsung_s6d7aa0x01_1280_800_video_on_cmd3, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd4), samsung_s6d7aa0x01_1280_800_video_on_cmd4, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd5), samsung_s6d7aa0x01_1280_800_video_on_cmd5, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd6), samsung_s6d7aa0x01_1280_800_video_on_cmd6, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd7), samsung_s6d7aa0x01_1280_800_video_on_cmd7, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd8), samsung_s6d7aa0x01_1280_800_video_on_cmd8, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd9), samsung_s6d7aa0x01_1280_800_video_on_cmd9, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd10), samsung_s6d7aa0x01_1280_800_video_on_cmd10, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd11), samsung_s6d7aa0x01_1280_800_video_on_cmd11, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd12), samsung_s6d7aa0x01_1280_800_video_on_cmd12, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd13), samsung_s6d7aa0x01_1280_800_video_on_cmd13, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd14), samsung_s6d7aa0x01_1280_800_video_on_cmd14, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd15), samsung_s6d7aa0x01_1280_800_video_on_cmd15, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd16), samsung_s6d7aa0x01_1280_800_video_on_cmd16, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd17), samsung_s6d7aa0x01_1280_800_video_on_cmd17, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd18), samsung_s6d7aa0x01_1280_800_video_on_cmd18, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd19), samsung_s6d7aa0x01_1280_800_video_on_cmd19, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd20), samsung_s6d7aa0x01_1280_800_video_on_cmd20, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd21), samsung_s6d7aa0x01_1280_800_video_on_cmd21, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd22), samsung_s6d7aa0x01_1280_800_video_on_cmd22, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd23), samsung_s6d7aa0x01_1280_800_video_on_cmd23, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd24), samsung_s6d7aa0x01_1280_800_video_on_cmd24, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd25), samsung_s6d7aa0x01_1280_800_video_on_cmd25, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd26), samsung_s6d7aa0x01_1280_800_video_on_cmd26, PANEL_DELAY},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd27), samsung_s6d7aa0x01_1280_800_video_on_cmd27, PANEL_DELAY},	
     /*CABC START*/
    {sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd28), samsung_s6d7aa0x01_1280_800_video_on_cmd28, PANEL_DELAY},	
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd29), samsung_s6d7aa0x01_1280_800_video_on_cmd29, PANEL_DELAY},
    {sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd30), samsung_s6d7aa0x01_1280_800_video_on_cmd30, PANEL_DELAY},
    {sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd31), samsung_s6d7aa0x01_1280_800_video_on_cmd31, PANEL_DELAY},
    {sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd32), samsung_s6d7aa0x01_1280_800_video_on_cmd32, PANEL_DELAY},
    {sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd33), samsung_s6d7aa0x01_1280_800_video_on_cmd33, PANEL_DELAY},
     /*CABC END*/
    {sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd34), samsung_s6d7aa0x01_1280_800_video_on_cmd34, 10},
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd35), samsung_s6d7aa0x01_1280_800_video_on_cmd35, 120},	
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd36), samsung_s6d7aa0x01_1280_800_video_on_cmd36, PANEL_DELAY},	
	{sizeof(samsung_s6d7aa0x01_1280_800_video_on_cmd37), samsung_s6d7aa0x01_1280_800_video_on_cmd37, 40},	
};

#define SAMSUNG_S6D7AA0X01_1280_800_VIDEO_ON_COMMAND ARRAY_SIZE(samsung_s6d7aa0x01_1280_800_video_on_command)


static char samsung_s6d7aa0x01_1280_800_video_off_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char samsung_s6d7aa0x01_1280_800_video_off_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd samsung_s6d7aa0x01_1280_800_video_off_command[] = {
	{0x4, samsung_s6d7aa0x01_1280_800_video_off_cmd0, 0x28},
	{0x4, samsung_s6d7aa0x01_1280_800_video_off_cmd1, 0x78}
};

#define SAMSUNG_S6D7AA0X01_1280_800_VIDEO_OFF_COMMAND ARRAY_SIZE(samsung_s6d7aa0x01_1280_800_video_off_command)


static struct command_state samsung_s6d7aa0x01_1280_800_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info samsung_s6d7aa0x01_1280_800_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info samsung_s6d7aa0x01_1280_800_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration samsung_s6d7aa0x01_1280_800_video_lane_config = {
	4, 0, 1, 1, 1, 1
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t samsung_s6d7aa0x01_1280_800_video_timings[] = {
	0x7B, 0x1A, 0x10, 0x00, 0x3C, 0x42, 0x14, 0x1C, 0x15, 0x03, 0x04, 0x00
};

static struct panel_timing samsung_s6d7aa0x01_1280_800_video_timing_info = {
	0, 4, 0x20, 0x3e
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence samsung_s6d7aa0x01_1280_800_video_reset_seq = {
	{1, 0, 1, }, {20, 20, 120, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight samsung_s6d7aa0x01_1280_800_video_backlight = {
  1, 1, 255, 100, 2, "PMIC_8941"
};
#endif /*_PANEL_SAMSUNG_S6D7AA0X01_1280_800_VIDEO_H_*/

