/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
/* zhouwentao modify porch for QL1000 onus hengkaihui hx8389b 2014.8.6*/
/*zhouwentao update para for onus hengkaihui 2014.8.6*/
/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_ST7703_HXGD_HD_5P5_VIDEO_H_

#define _PANEL_ST7703_HXGD_HD_5P5_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"
#define HXGD_ST7703_HD_5P5_VIDEO_SIGNATURE 0x38
#define HXGD_ST7703_HD_5P5_VIDEO_ID 0
#define HXGD_ST7703_HD_5P5_VIDEO_ADC_STATUS 0
#define	HXGD_ST7703_HD_5P5_VIDEO_IC_TYPE 7703
#define	HXGD_ST7703_HD_5P5_VIDEO_ADC_MAX  0
#define	HXGD_ST7703_HD_5P5_VIDEO_ADC_MIN   0

#define CMD_DELAY 0x10
/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config hxgd_st7703_hd_5p5_video_panel_data = {
  "qcom,mdss_dsi_st7703_hd_hxgd_5p5_hd_video", "dsi:0:", "qcom,mdss-dsi-panel",
  10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution hxgd_st7703_hd_5p5_video_panel_res = {
	720, 1280, 50, 50, 8, 0, 50, 50, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0
  
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info hxgd_st7703_hd_5p5_video_color = {
  24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/
static char mipi_st7703_hd_hxgd_cmd000[]={0x04, 0x00, 0x39, 0xC0, 0xB9, 0xF1, 0x12, 0x83};
static char mipi_st7703_hd_hxgd_cmd001[]={0x1C, 0x00, 0x39, 0xC0, 0xBA, 0x33, 0x81, 0x05, 0xF9, 0x0e, 0x0e, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x44, 0x25, 0x00, 0x91, 0x0a, 0x00, 0x00, 0x02, 0x4F, 0x11, 0x00, 0x00, 0x37};
static char mipi_st7703_hd_hxgd_cmd002[]={0x02, 0x00, 0x39, 0xC0, 0xB8, 0x25, 0xff, 0xff};		
static char mipi_st7703_hd_hxgd_cmd003[]={0x0B, 0x00, 0x39, 0xC0, 0xB3, 0x10, 0x10, 0x05, 0x05, 0x03, 0xFF, 0x00, 0x00, 0x00, 0x00, 0xff};
static char mipi_st7703_hd_hxgd_cmd004[]={0x0A, 0x00, 0x39, 0xC0, 0xC0, 0x70, 0x73, 0x50, 0x50, 0x00, 0x00, 0x08, 0x70, 0x00, 0xff, 0xff};
static char mipi_st7703_hd_hxgd_cmd005[]={0x02, 0x00, 0x39, 0xC0, 0xBC, 0x4E, 0xff, 0xff};
static char mipi_st7703_hd_hxgd_cmd006[]={0x02, 0x00, 0x39, 0xC0, 0xCC, 0x0B, 0xff, 0xff};
static char mipi_st7703_hd_hxgd_cmd007[]={0x02, 0x00, 0x39, 0xC0, 0xB4, 0x80, 0xff, 0xff};
static char mipi_st7703_hd_hxgd_cmd008[]={0x04, 0x00, 0x39, 0xC0, 0xB2, 0xC8, 0x02, 0x30};	
static char mipi_st7703_hd_hxgd_cmd009[]={0x0F, 0x00, 0x39, 0xC0, 0xE3, 0x07, 0x07, 0x0B, 0x0B, 0x03, 0x0B, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x80, 0xC0, 0x10, 0xff};
static char mipi_st7703_hd_hxgd_cmd010[]={0x0D, 0x00, 0x39, 0xC0, 0xC1, 0x54, 0xC0, 0x1E, 0x1E, 0x77, 0xE1, 0xFF, 0xFF, 0xCC, 0xCC, 0x77, 0x77, 0xff, 0xff, 0xff};
static char mipi_st7703_hd_hxgd_cmd011[]={0x03, 0x00, 0x39, 0xC0, 0xB5, 0x07, 0x07, 0xff};
static char mipi_st7703_hd_hxgd_cmd012[]={0x03, 0x00, 0x39, 0xC0, 0xB6, 0x30, 0x30, 0xff};
static char mipi_st7703_hd_hxgd_cmd013[]={0x04, 0x00, 0x39, 0xC0, 0xBF, 0x02, 0x11, 0x00};
static char mipi_st7703_hd_hxgd_cmd014[]={0x40, 0x00, 0x39, 0xC0, 0xE9, 0XC2, 0x10, 0x04, 0x05, 0x00, 0x0A, 0xA0, 0x12, 0x31, 0x23, 0x37, 0x82, 0x40, 0xA0, 0x27, 0x38, 0x0C, 0x00, 0x03, 0x00, 0x00, 0x00, 0x0C, 0x00, 0x03, 0x00, 0x00, 0x00, 0x75, 0x75, 0x31, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x13, 0x88, 0x64, 0x64, 0x20, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x02, 0x88, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static char mipi_st7703_hd_hxgd_cmd015[]={0x3E, 0x00, 0x39, 0xC0, 0xEA, 0x02, 0x21, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x46, 0x02, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x64, 0x88, 0x13, 0x57, 0x13, 0x88, 0x88, 0x88, 0x88, 0x88, 0x88, 0x75, 0x88, 0x23, 0x10, 0x00, 0x00, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x0A, 0xA0, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff};
static char mipi_st7703_hd_hxgd_cmd016[]={0x23, 0x00, 0x39, 0xC0, 0xE0, 0x00, 0x0B, 0x0E, 0x28, 0x32, 0x3C, 0x40, 0x31, 0x08, 0x0C, 0x0D, 0x10, 0x11, 0x0F, 0x11, 0x10, 0x10, 0x00, 0x0B, 0x0E, 0x28, 0x32, 0x3C, 0x40, 0x31, 0x08, 0x0C, 0x0D, 0x10, 0x11, 0x0F, 0x11, 0x10, 0x10, 0xff};
static char mipi_st7703_hd_hxgd_cmd017[]={0x03, 0x00, 0x39, 0xC0, 0xC7, 0xA0, 0x00, 0xff};
static char mipi_st7703_hd_hxgd_cmd018[]={0x05, 0x00, 0x39, 0xC0, 0xC8, 0x01, 0x02, 0x04, 0x02, 0xff, 0xff, 0xff};  	
static char mipi_st7703_hd_hxgd_cmd019[]={0x02, 0x00, 0x39, 0xC0, 0x53, 0x24, 0xff, 0xff};
static char mipi_st7703_hd_hxgd_cmd020[]={0x02, 0x00, 0x39, 0xC0, 0x55, 0x01, 0xff, 0xff};
static char mipi_st7703_hd_hxgd_cmd021[]={0x02,0x00,0x39,0xC0,0x11,0x00,0xFF,0xFF};
static char mipi_st7703_hd_hxgd_cmd022[]={0x02,0x00,0x39,0xC0,0x29,0x00,0xFF,0xFF};

static struct mipi_dsi_cmd hxgd_st7703_hd_5p5_video_on_command[] = {
{sizeof(mipi_st7703_hd_hxgd_cmd000), (char *)mipi_st7703_hd_hxgd_cmd000,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd001), (char *)mipi_st7703_hd_hxgd_cmd001,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd002), (char *)mipi_st7703_hd_hxgd_cmd002,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd003), (char *)mipi_st7703_hd_hxgd_cmd003,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd004), (char *)mipi_st7703_hd_hxgd_cmd004,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd005), (char *)mipi_st7703_hd_hxgd_cmd005,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd006), (char *)mipi_st7703_hd_hxgd_cmd006,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd007), (char *)mipi_st7703_hd_hxgd_cmd007,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd008), (char *)mipi_st7703_hd_hxgd_cmd008,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd009), (char *)mipi_st7703_hd_hxgd_cmd009,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd010), (char *)mipi_st7703_hd_hxgd_cmd010,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd011), (char *)mipi_st7703_hd_hxgd_cmd011,CMD_DELAY},

{sizeof(mipi_st7703_hd_hxgd_cmd012), (char *)mipi_st7703_hd_hxgd_cmd012,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd013), (char *)mipi_st7703_hd_hxgd_cmd013,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd014), (char *)mipi_st7703_hd_hxgd_cmd014,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd015), (char *)mipi_st7703_hd_hxgd_cmd015,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd016), (char *)mipi_st7703_hd_hxgd_cmd016,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd017), (char *)mipi_st7703_hd_hxgd_cmd017,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd018), (char *)mipi_st7703_hd_hxgd_cmd018,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd019), (char *)mipi_st7703_hd_hxgd_cmd019,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd020), (char *)mipi_st7703_hd_hxgd_cmd020,CMD_DELAY},
{sizeof(mipi_st7703_hd_hxgd_cmd021), (char *)mipi_st7703_hd_hxgd_cmd021,150},
{sizeof(mipi_st7703_hd_hxgd_cmd022), (char *)mipi_st7703_hd_hxgd_cmd022,50},
};

#define HXGD_ST7703_HD_5P5_VIDEO_ON_COMMAND  ARRAY_SIZE(hxgd_st7703_hd_5p5_video_on_command)

static char hxgd_st7703_hd_5p5_videooff_cmd0[] = {
0x28, 0x00, 0x05, 0x80 };


static char hxgd_st7703_hd_5p5_videooff_cmd1[] = {
0x10, 0x00, 0x05, 0x80 };




static struct mipi_dsi_cmd hxgd_st7703_hd_5p5_video_off_command[] = {
{ 0x4 , hxgd_st7703_hd_5p5_videooff_cmd0},
{ 0x4 , hxgd_st7703_hd_5p5_videooff_cmd1}
};
#define HXGD_ST7703_HD_5P5_VIDEO_OFF_COMMAND 2


static struct command_state hxgd_st7703_hd_5p5_video_state = {
  0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info hxgd_st7703_hd_5p5_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info hxgd_st7703_hd_5p5_video_video_panel = {
  1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration hxgd_st7703_hd_5p5_video_lane_config = {
  4, 0, 1, 1, 1, 1
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
const uint32_t hxgd_st7703_hd_5p5_video_timings[] = {
  0xE7,0x36,0x24,0x00,0x66,0x6A,0x2A,0x3A,0x2D,0x03,0x04,0x00
};



static struct mipi_dsi_cmd hxgd_st7703_hd_5p5_video_rotation[] = {

};
#define HXGD_ST7703_HD_5P5_VIDEO_ROTATION 0


static struct panel_timing hxgd_st7703_hd_5p5_video_timing_info = {
  0, 4, 0x03, 0x35
};

static struct panel_reset_sequence hxgd_st7703_hd_5p5_video_panel_reset_seq = {
{ 1, 0, 1, }, { 50, 50, 150, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight hxgd_st7703_hd_5p5_video_backlight = {
  1, 1, 255, 100, 2, "PMIC_8941"
};


#endif /*_PANEL_ST7703_HXGD_HD_5P5_VIDEO_H_*/
